/**:
  ros__parameters:
    cube2_goal:
      goal_0:          
        id: 2
        position: [3.75, -7.75]            
        orientation: [0.7071, 0.0, 0.0, 0.7071]  
        circular_direction: 0        
      goal_1:         
        id: 4
        position: [2.5, -6.5]
        orientation: [1.0,0.0,0.0,0.0]
        circular_direction: 1
      goal_2:          
        id: 5
        position: [3.75, -5.25]
        orientation: [0.7071, 0.0, 0.0, -0.7071]
        circular_direction: 0
      goal_3:          
        id: 6
        position: [5, -6.5]
        orientation: [0.0, 0.0, 0.0, 1.0]
        circular_direction: 1

    final_goal:
      "2":
        position: [-1.8, 2.1]
        orientation: [1.0, 0.0, 0.0, 0.0]
      "4":
        position: [-8.0, -2.1]
        orientation: [1.0, 0.0, 0.0, 0.0]
      "5":
        position: [-6.0, -9.0]
        orientation: [1.0, 0.0, 0.0, 0.0]
      "6":
        position: [8.5, 8.5]
        orientation: [1.0, 0.0, 0.0, 0.0]
